### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mfpiccolo** [servo/rust-selectors#35]
It would be really great if there were some examples of how to use this library.  Not sure that it belongs in this repo but including how to use it in conjunction with html5ever or other servo components could be very useful as well.

**Comment by SimonSapin** [comment]
I agree that documentation (including examples) is sorely needed. This library has recently (in terms of work done since) been extracted from Servo, where is was initially "not intended for public consumption" :)

In the meantime, have a look at https://github.com/SimonSapin/kuchiki . (Which also has no docs and is still in early exploratory stages, sorry!)

**Comment by mfpiccolo** [comment]
No docs but these tests files look useful.  
https://github.com/SimonSapin/kuchiki/blob/master/src/tests.rs
Thanks.  And keep up the good work. :smile:
